# print(string,end="")
# "                `         `                "
# ";,,,             `       `             ,,,;"
# ":YES8888bo.       :     :       .od8888YES:"
# "  888IO8DO88b.     :   :     .d8888I8DO88  "
# "  8LOVEY'  `Y8b.   `   '   .d8Y'  `YLOVE8  "
# " jTHEE!  .db.  Yb. '   ' .dY  .db.  8THEE! "
# "   `888  Y88Y    `b ( ) d'    Y88Y  888'   "
# "    8MYb  '`        ,',        `'  dMY8    "
# "   j8prECIOUSgf"''  ':'  ``"?g8prECIOUSk   "
# "     'Y'   .8'     d' 'b     '8.   'Y'     "
# "      !   .8' db  d'; ;`b  db '8.   !      "
# "         d88  `'  8 ; ; 8  `'  88b         "
# "        d88Ib   .g8 ',' 8g.   dI88b        "
# "       :888LOVE88Y'     'Y88LOVE888:       "
# "       '! THEE888'       `888THEE !'       "
# "          '8Y  `Y         Y'  Y8'          "
# "           Y                   Y           "
# "           !                   !           "

def print_characters(character, num_times):
  x = num_times
  while x != 0:    
    print(character,end="")
    x -= 1

print_characters(' ', 16)
print_characters('`', 1)
print_characters(' ', 9)
print_characters("'", 1)
print_characters(' ', 16)
print('')
print_characters(';', 1)
print_characters(',', 3)
print_characters(' ', 13)
print_characters('`', 1)
print_characters(' ', 7)
print_characters("'", 1)
print_characters(' ', 13)
print_characters(',', 3)
print_characters(';', 1)
print('')
print_characters(':', 1)
print_characters('Y', 1)
print_characters('E', 1)
print_characters('S', 1)
print_characters('8', 4)
print_characters('b', 1)
print_characters('o', 1)
print_characters('.', 1)
print_characters(' ', 7)
print_characters(':', 1)
print_characters(' ', 5)
print_characters(':', 1)
print_characters(' ', 7)
print_characters('.', 1)
print_characters('o', 1)
print_characters('d', 1)
print_characters('8', 4)
print_characters('S', 1)
print_characters('E', 1)
print_characters('Y', 1)
print_characters(':', 1)
print('')
print_characters(' ', 1)
print_characters('`', 1)
print_characters('8', 3)
print_characters('I', 1)
print_characters('O', 1)
print_characters('8', 1)
print_characters('D', 1)
print_characters('O', 1)
print_characters('8', 2)
print_characters('b', 1)
print_characters('.', 1)
print_characters(' ', 5)
print_characters(':', 1)
print_characters(' ', 3)
print_characters(':', 1)
print_characters(' ', 5)
print_characters('.', 1)
print_characters('d', 1)
print_characters('8', 4)
print_characters('I', 1)
print_characters('8', 1)
print_characters('D', 1)
print_characters('O', 1)
print_characters('8', 2)
print_characters('`', 1)
print_characters(' ', 1)
print('')
print_characters(' ', 2)
print_characters('8', 1)
print_characters('L', 1)
print_characters('O', 1)
print_characters('V', 1)
print_characters('E', 1)
print_characters('Y', 1)
print_characters('`', 1)
print_characters(' ', 2)
print_characters("'", 1)
print_characters('Y', 1)
print_characters('8', 1)
print_characters('b', 1)
print_characters('.', 1)
print_characters(' ', 3)
print_characters('`', 1)
print_characters(' ', 3)
print_characters('`', 1)
print_characters(' ', 3)
print_characters('.', 1)
print_characters('d', 1)
print_characters('8', 1)
print_characters('Y', 1)
print_characters("'", 1)
print_characters(' ', 2)
print_characters('`', 1)
print_characters('Y', 1)
print_characters('E', 1)
print_characters('V', 1)
print_characters('O', 1)
print_characters('L', 1)
print_characters('8', 1)
print_characters(' ', 2)
print('')
print_characters(' ', 1)
print_characters('!', 1)
print_characters('V', 1)
print_characters('E', 1)
print_characters('P', 1)
print_characters('V', 1)
print_characters('8', 1)
print_characters(' ', 2)
print_characters('.', 1)
print_characters('d', 1)
print_characters('b', 1)
print_characters('.', 1)
print_characters(' ', 2)
print_characters('Y', 1)
print_characters('b', 1)
print_characters('.', 1)
print_characters(' ', 2)
print_characters('`', 1)
print_characters(' ', 1)
print_characters('`', 1)
print_characters(' ', 2)
print_characters('.', 1)
print_characters('d', 1)
print_characters('Y', 1)
print_characters(' ', 2)
print_characters('.', 1)
print_characters('d', 1)
print_characters('b', 1)
print_characters('.', 1)
print_characters(' ', 2)
print_characters('8', 1)
print_characters('V', 1)
print_characters('P', 1)
print_characters('E', 1)
print_characters('V', 1)
print_characters('!', 1)
print_characters(' ', 1)
print('')
print_characters(' ', 3)
print_characters('`', 1)
print_characters('8', 3)
print_characters(' ', 2)
print_characters('Y', 1)
print_characters('8', 2)
print_characters('Y', 1)
print_characters(' ', 4)
print_characters('`', 1)
print_characters('b', 1)
print_characters(' ', 1)
print_characters('(', 1)
print_characters(' ', 1)
print_characters(')', 1)
print_characters(' ', 1)
print_characters('d', 1)
print_characters('`', 1)
print_characters(' ', 4)
print_characters('Y', 1)
print_characters('8', 2)
print_characters('Y', 1)
print_characters(' ', 2)
print_characters('8', 3)
print_characters('`', 1)
print_characters(' ', 3)
print('')
print_characters(' ', 4)
print_characters('8', 1)
print_characters('M', 1)
print_characters('Y', 1)
print_characters('b', 1)
print_characters(',', 1)
print_characters(' ', 1)
print_characters("'", 1)
print_characters('`', 1)
print_characters(' ', 8)
print_characters(',', 1)
print_characters('`', 1)
print_characters(',', 1)
print_characters(' ', 8)
print_characters('`', 1)
print_characters("'", 1)
print_characters(' ', 1)
print_characters(',', 1)
print_characters('d', 1)
print_characters('Y', 1)
print_characters('M', 1)
print_characters('8', 1)
print_characters(' ', 4)
print('')
print_characters(' ', 3)
print_characters('x', 1)
print_characters('8', 4)
print_characters('E', 2)
print_characters('m', 1)
print_characters('e', 1)
print_characters('8', 1)
print_characters('9', 1)
print_characters('?', 1)
print_characters('"', 1)
print_characters("'", 2)
print_characters(' ', 2)
print_characters('`', 1)
print_characters(':', 1)
print_characters('`', 1)
print_characters(' ', 2)
print_characters('`', 2)
print_characters('"', 1)
print_characters('?', 1)
print_characters('9', 1)
print_characters('8', 1)
print_characters('e', 1)
print_characters('m', 1)
print_characters('E', 2)
print_characters('8', 4)
print_characters('x', 1)
print_characters(' ', 3)
print('')
print_characters(' ', 5)
print_characters('"', 1)
print_characters('Y', 1)
print_characters('"', 1)
print_characters(' ', 3)
print_characters('.', 1)
print_characters('8', 1)
print_characters("'", 1)
print_characters(' ', 5)
print_characters('d', 1)
print_characters("'", 1)
print_characters(' ', 1)
print_characters("'", 1)
print_characters('b', 1)
print_characters(' ', 5)
print_characters("'", 1)
print_characters('8', 1)
print_characters('.', 1)
print_characters(' ', 3)
print_characters('"', 1)
print_characters('Y', 1)
print_characters('"', 1)
print_characters(' ', 5)
print('')
print_characters(' ', 6)
print_characters('!', 1)
print_characters(' ', 3)
print_characters('.', 1)
print_characters('8', 1)
print_characters("'", 1)
print_characters(' ', 1)
print_characters('d', 1)
print_characters('b', 1)
print_characters(' ', 2)
print_characters('d', 1)
print_characters("'", 1)
print_characters(';', 1)
print_characters(' ', 1)
print_characters(';', 1)
print_characters("'", 1)
print_characters('b', 1)
print_characters(' ', 2)
print_characters('d', 1)
print_characters('b', 1)
print_characters(' ', 1)
print_characters("'", 1)
print_characters('8', 1)
print_characters('.', 1)
print_characters(' ', 3)
print_characters('!', 1)
print_characters(' ', 6)
print('')
print_characters(' ', 9)
print_characters('d', 1)
print_characters('8', 2)
print_characters(' ', 2)
print_characters('`', 1)
print_characters("'", 1)
print_characters(' ', 2)
print_characters('8', 1)
print_characters(' ', 1)
print_characters(';', 1)
print_characters(' ', 1)
print_characters(';', 1)
print_characters(' ', 1)
print_characters('8', 1)
print_characters(' ', 2)
print_characters("'", 1)
print_characters('`', 1)
print_characters(' ', 2)
print_characters('8', 2)
print_characters('b', 1)
print_characters(' ', 9)
print('')
print_characters(' ', 8)
print_characters('d', 1)
print_characters('8', 2)
print_characters('I', 1)
print_characters('b', 1)
print_characters(' ', 3)
print_characters('.', 1)
print_characters('g', 1)
print_characters('8', 1)
print_characters(' ', 1)
print_characters("'", 1)
print_characters(',', 1)
print_characters("'", 1)
print_characters(' ', 1)
print_characters('8', 1)
print_characters('g', 1)
print_characters('.', 1)
print_characters(' ', 3)
print_characters('d', 1)
print_characters('I', 1)
print_characters('8', 2)
print_characters('b', 1)
print_characters(' ', 8)
print('')
print_characters(' ', 7)
print_characters(':', 1)
print_characters('8', 3)
print_characters('O', 2)
print_characters('V', 2)
print_characters('8', 2)
print_characters('Y', 1)
print_characters("'", 1)
print_characters(' ', 5)
print_characters("'", 1)
print_characters('Y', 1)
print_characters('8', 2)
print_characters('V', 2)
print_characters('O', 2)
print_characters('8', 3)
print_characters(':', 1)
print_characters(' ', 7)
print('')
print_characters(' ', 7)
print_characters('`', 1)
print_characters('!', 1)
print_characters(' ', 1)
print_characters('V', 1)
print_characters('O', 2)
print_characters('E', 1)
print_characters('8', 3)
print_characters("'", 1)
print_characters(' ', 7)
print_characters('`', 1)
print_characters('8', 3)
print_characters('E', 1)
print_characters('V', 1)
print_characters(' ', 1)
print_characters('!', 1)
print_characters("'", 1)
print_characters(' ', 7)
print('')
print_characters(' ', 10)
print_characters("'", 1)
print_characters('8', 1)
print_characters('Y', 1)
print_characters(' ', 2)
print_characters('`', 1)
print_characters('Y', 1)
print_characters(' ', 9)
print_characters('Y', 1)
print_characters('`', 1)
print_characters(' ', 2)
print_characters('Y', 1)
print_characters('8', 1)
print_characters("'", 1)
print_characters(' ', 10)
print('')
print_characters(' ', 11)
print_characters('Y', 1)
print_characters(' ', 19)
print_characters('Y', 1)
print_characters(' ', 11)
print('')
print_characters(' ', 11)
print_characters('!', 1)
print_characters(' ', 19)
print_characters('!', 1)
print_characters(' ', 11)